---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.elasticsearch.username | b64enc }}
  password: {{ .Values.elasticsearch.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: thm-fluentd-secret-docker
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: helm
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret | b64enc }}