apiVersion: v1
kind: Service
metadata:
  name: fluentd-svc
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: fluentd-logging
spec:
  type: ClusterIP
  selector:
    k8s-app: fluentd-logging
  ports:
  - name: fluentd-source
    port: 24220
    targetPort: fluentd-source
    protocol: TCP