service:
  type: ClusterIP

resources:
  limits:
    cpu: 200m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector:
  node-group: mgmt

tolerations:
  - key: "node-role.kubernetes.io/management"
    operator: "Exists"
    effect: "NoSchedule"

env:
  - name: FLUENT_ELASTICSEARCH_HOST
    value: "elasticsearch-master.logging.svc.cluster.local"
  - name: FLUENT_ELASTICSEARCH_PORT
    value: "9200"
  - name: FLUENT_ELASTICSEARCH_SCHEME
    value: "https"
  - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
    value: "false"
  - name: FLUENT_ELASTICSEARCH_SSL_VERSION
    value: "TLSv1_2"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: NotIn
              values:
                - ap-northeast-2b