resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector:
  node-group: mgmt

args:
  - --kubelet-preferred-address-types=InternalIP
  - --kubelet-insecure-tls
  - --metric-resolution=15s

image:
  repository: registry.k8s.io/metrics-server/metrics-server
  tag: v0.7.1

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /livez
    port: https
    scheme: HTTPS
  periodSeconds: 10

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /readyz
    port: https
    scheme: HTTPS
  initialDelaySeconds: 20
  periodSeconds: 10