releases:
  - name: fluentd
    namespace: logging
    chart: fluent/fluentd
    version: 0.5.0
    values:
      - ../values/fluentd-values.yaml
    createNamespace: true
    set:
      - name: nodeSelector.node-group
        value: mgmt
      - name: resources.requests.cpu
        value: 100m
      - name: resources.requests.memory
        value: 200Mi
      - name: resources.limits.memory
        value: 400Mi