releases:
  - name: istio-ingress
    namespace: istio-ingress
    chart: istio/gateway
    version: 1.22.1
    createNamespace: true
    needs:
      - istio-system/istiod
    values:
      - ../values/ingress-values.yaml
    set:
      - name: nodeSelector.node-group
        value: mgmt
      - name: service.type
        value: LoadBalancer
      - name: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-type
        value: nlb
      - name: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-scheme
        value: internet-facing